services:
  python:
    image: python
    build: ./python
    container_name: "python_sandbox"
    stdin_open: true
    tty: true
    working_dir: "/tmp/work"
    volumes:
      - ../python:/tmp/work
